### ISSUE TITLE
standardplots labels at bottom of plot appear to be written multiple times

### ISSUE THREAD

**Issue by jaythespacehound** [haavee/jiveplot#8]
In the pgplot version at least.
The bottom labels appear to be overwriting themselves somehow.
This causes the labels to appear thick/blurry and hard to read.
Applies to all plot types. 
See attached images.

[ry007b-cross-0.pdf](https://github.com/haavee/jiveplot/files/2690811/ry007b-cross-0.pdf)
![labelsblurry](https://user-images.githubusercontent.com/3013142/50159215-79216780-02d6-11e9-94b7-53f7cbb8c7cc.png)

**Comment by haavee** [comment]
I can't replicate this. I used RSY007B/rsy007b.ms and what I observed was that the source labels in the amplitude panel overwrite but that is probably because on this x-axis scale the scan duration is significantly shorter than the source label.
E.g. the "AT2018" string, measured in x-axis world coordinates is about half an hour. If within that half an hour there are three or more scans on other sources, the source labels for scan numbers 4 and up will start overwriting those of scan numbers 1, 2, and 3; the source-name display cycles over three different y-heights.

As for the labels in the legend I don't see this happening in my master branch. I have attached a screenshot of how the plot came out on my config: EEE2, git pull & checkout master, /usr/bin/python, PPGPLOT backend. You can see the labels being _dense_ but not the same label overwriting itself.
![screen shot 2018-12-21 at 09 33 00](https://user-images.githubusercontent.com/14309703/50332905-d3534000-0503-11e9-9fd4-eeea0029bbf0.png)

**Comment by jaythespacehound** [comment]
This only happens when saving (tested PS and PNG)
Does not occur for Giza but this might be because giza does not respect ptsz.

**Comment by haavee** [comment]
Turns out they weren't painted twice. The linewidth was set to "4" when drawing PGTXT() and to screen that made no difference to when plotting to file PGPLOT suddenly starts to honour that attribute and draw the text in (very) bold characters.
Is now fixed by alternating line width between line and text to an appropriate setting.
